pub mod agent_schema;
pub mod alias;
pub mod analyses;
pub mod artifacts;
#[cfg(feature = "embed")]
pub mod backfill_tasks;
pub mod config;
pub mod documents;

pub mod daemon;
pub mod daemon_service;
pub mod docs;
#[cfg(feature = "embed")]
pub mod doctor;
pub mod hooks;
pub mod id;
pub mod import_beads;
#[cfg(feature = "embed")]
pub mod index;
pub mod init;
pub mod jobs;
pub mod link;
pub mod mcp;
pub mod mcp_setup;
#[cfg(feature = "embed")]
pub mod memory;
pub mod migrate;
pub mod plans;
pub mod plugin;
pub mod provider;
pub mod records;
pub mod registry;
#[cfg(feature = "embed")]
pub mod reindex;
pub mod rpc_client;
pub mod sagas;
pub mod snapshots;
pub mod status;
pub mod tags;
pub mod tasks;
#[cfg(feature = "embed")]
pub mod vacuum;
#[cfg(feature = "embed")]
pub mod watch;
